// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKlhdHIejMWg6XfevnuiLfdIULbSd_7A',
    appId: '1:903369669754:web:56f2bf16f36cc053b24fc3',
    messagingSenderId: '903369669754',
    projectId: 'locksense-c23a8',
    authDomain: 'locksense-c23a8.firebaseapp.com',
    databaseURL: 'https://locksense-c23a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locksense-c23a8.appspot.com',
    measurementId: 'G-59LX25PBD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKDYIJr2A2Vb1fRqt5qzlqG_StEwWwis',
    appId: '1:903369669754:android:b9d8b7acd111f702b24fc3',
    messagingSenderId: '903369669754',
    projectId: 'locksense-c23a8',
    databaseURL: 'https://locksense-c23a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locksense-c23a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6hN_HD1drcneE3Kb7njPasjL4-VKvXY',
    appId: '1:903369669754:ios:4405c0567e8bf739b24fc3',
    messagingSenderId: '903369669754',
    projectId: 'locksense-c23a8',
    databaseURL: 'https://locksense-c23a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locksense-c23a8.appspot.com',
    iosClientId: '903369669754-6o9gkd7bpd02s60qnt9pb1ppta6ni5ef.apps.googleusercontent.com',
    iosBundleId: 'com.locksense.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6hN_HD1drcneE3Kb7njPasjL4-VKvXY',
    appId: '1:903369669754:ios:4405c0567e8bf739b24fc3',
    messagingSenderId: '903369669754',
    projectId: 'locksense-c23a8',
    databaseURL: 'https://locksense-c23a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locksense-c23a8.appspot.com',
    iosClientId: '903369669754-6o9gkd7bpd02s60qnt9pb1ppta6ni5ef.apps.googleusercontent.com',
    iosBundleId: 'com.locksense.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeKlhdHIejMWg6XfevnuiLfdIULbSd_7A',
    appId: '1:903369669754:web:eb5c7b3fd1a75e05b24fc3',
    messagingSenderId: '903369669754',
    projectId: 'locksense-c23a8',
    authDomain: 'locksense-c23a8.firebaseapp.com',
    databaseURL: 'https://locksense-c23a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locksense-c23a8.appspot.com',
    measurementId: 'G-SH4Y557VJG',
  );

}