name: CI-CD pipeline

on:
  pull_request:
    types: [opened, synchronize, closed]
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  CD:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
    needs: [CI]
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: locksense-${{ github.sha }}
          path: app/build/app/outputs/flutter-apk/app-release.apk
      - name: Build Web
        run: flutter build web
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOCKSENSE_C23A8 }}
          projectId: locksense-c23a8
          entryPoint: "./app"
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
