name: CI-CD pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk --debug

  CD:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.merged == true }}
    needs: [CI]
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      # - name: Deploy to Firebase
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: ${{ secrets.GITHUB_TOKEN }}
      #     firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOCKSENSE_C23A8 }}
      #     projectId: locksense-c23a8
      #     entryPoint: "./app"
