name: Release New Version

on:
  push:
    branches:
      - main
      - dev
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
      - name: Install dependencies
        run: npm install
      - name: Get dependencies
        run: flutter pub get
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: npx semantic-release
