name: Test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
